apiVersion: v1
kind: Service
metadata:
  labels:
    app: arrival
  name: arrival-lite
  namespace: default
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8081
  selector:
    app: arrival
  sessionAffinity: None
  type: LoadBalancer
